BEGIN TRANSACTION;

CREATE TABLE LUGAR(
    LOCALIZACAO serial PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    INFO VARCHAR(255) NOT NULL,
	MAPA VARCHAR(255) NOT NULL
);

CREATE TABLE CAMINHOS(
	SALA_ATUAL int NOT NULL,
	PROXIMA_SALA int NOT NULL,
    CONSTRAINT PK_CAMINHOS PRIMARY KEY(SALA_ATUAL, PROXIMA_SALA),
    CONSTRAINT FK_SALA_ATUAL FOREIGN KEY (SALA_ATUAL) REFERENCES LUGAR(LOCALIZACAO),
    CONSTRAINT FK_PROXIMA_SALA FOREIGN KEY (PROXIMA_SALA) REFERENCES LUGAR(LOCALIZACAO)
);

CREATE TABLE TREINADOR (
    TREINADOR_ID serial PRIMARY KEY NOT NULL,
    NOME_TREINADOR VARCHAR(50) NOT NULL,
    LOCALIZACAO int,
    INSIGNIAS int,
    POKEMONS_CAPTURADOS int NOT NULL,
    REGISTROS_POKEDEX int NOT NULL,
    DINHEIRO int NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CONSTRAINT FK_LOCAL_TREINADOR FOREIGN KEY(LOCALIZACAO) REFERENCES LUGAR(LOCALIZACAO)
);

CREATE TABLE ITENS_COMUNS(
    NOME_ITEM VARCHAR(60) PRIMARY KEY,
    EFEITO VARCHAR(150)
);

CREATE TABLE ITENS_CHAVE(
    NOME_ITEM VARCHAR(60) PRIMARY KEY,
    UTILIDADE VARCHAR(150)
);

CREATE TABLE FRUTAS(
    NOME_ITEM VARCHAR(60) PRIMARY KEY,
    EFEITO VARCHAR(150)
);

CREATE TABLE TIPO(
    TIPO_ID serial PRIMARY KEY,
    NOME_TIPO VARCHAR(10) NOT NULL,
    CONSTRAINT SK_NOME_TIPO UNIQUE (NOME_TIPO)
);

CREATE TABLE EFEITO(
    EFEITO_ID SERIAL PRIMARY KEY,
    NOME_EFEITO VARCHAR(10) NOT NULL,
    ACURACIA SMALLINT NOT NULL,
    DANO SMALLINT,
    INFO VARCHAR(150) NOT NULL,
    CONSTRAINT SK_NOME_EFEITO UNIQUE (NOME_EFEITO)
);

CREATE TABLE HABILIDADE(
    HABILIDADE_ID serial PRIMARY KEY,
    NOME_HABILIDADE VARCHAR(20) NOT NULL,
    ALCANCE CHAR(1),
    DANO SMALLINT,
    TIPO int NOT NULL,
    ACURACIA int NOT NULL,
    EFEITO SMALLINT,
    INFO VARCHAR(150) NOT NULL,
    CONSTRAINT NOME_HABILIDADE_SK UNIQUE (NOME_HABILIDADE),
    CONSTRAINT FK_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO (TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_EFEITO FOREIGN KEY (EFEITO) REFERENCES EFEITO (EFEITO_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE TMS(
    NOME_ITEM VARCHAR(60) PRIMARY KEY,
    HABILIDADE_ID int NOT NULL,
    CONSTRAINT HABILIDADE_FK FOREIGN KEY (HABILIDADE_ID) REFERENCES HABILIDADE (HABILIDADE_ID),
    CONSTRAINT SK_HABILIDADE UNIQUE (HABILIDADE_ID)
);

CREATE TABLE POKEBOLAS(
    NOME_ITEM VARCHAR(60) PRIMARY KEY,
    FORCA SMALLINT NOT NULL
);

CREATE TABLE MOCHILA(
    DONO int NOT NULL,
    NOME_ITEM VARCHAR(60) NOT NULL,
    QUANTIDADE SMALLINT,
    ORIGEM VARCHAR(15) NOT NULL,
    CONSTRAINT PK_MOCHILA PRIMARY KEY (NOME_ITEM),
    CONSTRAINT FK_ITEM_CHAVE FOREIGN KEY (NOME_ITEM) REFERENCES ITENS_CHAVE(NOME_ITEM),
    CONSTRAINT FK_ITEM_COMUM FOREIGN KEY (NOME_ITEM) REFERENCES ITENS_COMUNS(NOME_ITEM),
    CONSTRAINT FK_ITEM_TMS FOREIGN KEY (NOME_ITEM) REFERENCES TMS(NOME_ITEM),
    CONSTRAINT FK_ITEM_POKEBOLAS FOREIGN KEY (NOME_ITEM) REFERENCES POKEBOLAS(NOME_ITEM),
    CONSTRAINT FK_ITEM_FRUTAS FOREIGN KEY (NOME_ITEM) REFERENCES FRUTAS(NOME_ITEM),
    CONSTRAINT UNQ_DONO_MOCHILA UNIQUE (ORIGEM),
    CONSTRAINT FK_DONO FOREIGN KEY (DONO) REFERENCES TREINADOR (TREINADOR_ID)
);


CREATE TABLE POKEDEX(
	NUMERO_POKEDEX int PRIMARY KEY,
	NOME_POKEMON VARCHAR(20),
	TIPO1 int NOT NULL,
	TIPO2 int,
	SOM_EMITIDO int,
	REGIAO VARCHAR(20),
	TAXA_CAPTURA smallint NOT NULL,
	NIVEL_EVOLUCAO SMALLINT,
	INFO VARCHAR(100),
	PESQUISA int,
    CONSTRAINT FK_TIPO1_POKEDEX FOREIGN KEY (TIPO1) REFERENCES TIPO (TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_TIPO2_POKEDEX FOREIGN KEY (TIPO2) REFERENCES TIPO (TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE EVOLUCOES(
	ANTERIOR int PRIMARY KEY,
	SUCESSOR int NOT NULL,
	CONSTRAINT FK_ANTERIOR FOREIGN KEY (ANTERIOR) REFERENCES POKEDEX (NUMERO_POKEDEX) ON DELETE CASCADE,
	CONSTRAINT FK_SUCESSOR FOREIGN KEY (SUCESSOR) REFERENCES POKEDEX (NUMERO_POKEDEX) ON DELETE CASCADE
);
CREATE TABLE POKEMONS_DESCOBERTOS(
	NUMERO_POKEMON int PRIMARY KEY,
	TREINADOR_ID int,

	CONSTRAINT FK_NUMERO_POKEDEX FOREIGN KEY(NUMERO_POKEMON) REFERENCES POKEDEX(NUMERO_POKEDEX),
	CONSTRAINT FK_TREINADOR_ID FOREIGN KEY (TREINADOR_ID) REFERENCES TREINADOR(TREINADOR_ID)

);

CREATE TABLE POKEMON(
    POKEMON_ID serial PRIMARY KEY,
    NUMERO_POKEDEX int,
	TREINADOR_ID int,
    HABILIDADE1 VARCHAR(20),
    HABILIDADE2 VARCHAR(20),
    HABILIDADE3 VARCHAR(20),
    HABILIDADE4 VARCHAR(20),
	NATURE VARCHAR(10) NOT NULL,
    NIVEL smallint NOT NULL,
	XP SMALLINT NOT NULL,
    HP smallint NOT NULL,
    DEFESA smallint NOT NULL,
	ATAQUE smallint NOT NULL,
	SP_ATAQUE smallint NOT NULL,
	SP_DEFESA smallint NOT NULL,
	VELOCIDADE smallint NOT NULL,
	ACURACIA smallint NOT NULL,
	SEXO CHAR(1) NOT NULL,
	STATUS VARCHAR(20),
	POKEBOLA VARCHAR(60),
	ALTURA smallint NOT NULL,
	PESO smallint NOT NULL,
	LOCALIZACAO int,
    CONSTRAINT FK_LOCALIZACAO FOREIGN KEY (LOCALIZACAO) REFERENCES LUGAR(LOCALIZACAO),
    CONSTRAINT FK_TREINADOR_ID FOREIGN KEY (TREINADOR_ID) REFERENCES TREINADOR(TREINADOR_ID),
    CONSTRAINT FK_CAPTURADO_POKEBOLA FOREIGN KEY (POKEBOLA) REFERENCES POKEBOLAS(NOME_ITEM),
    CONSTRAINT FK_NUM_POKEDEX FOREIGN KEY (NUMERO_POKEDEX) REFERENCES POKEDEX(NUMERO_POKEDEX),
    CONSTRAINT FK_HABILIDADE1 FOREIGN KEY (HABILIDADE1) REFERENCES HABILIDADE(NOME_HABILIDADE),
    CONSTRAINT FK_HABILIDADE2 FOREIGN KEY (HABILIDADE2) REFERENCES HABILIDADE(NOME_HABILIDADE),
    CONSTRAINT FK_HABILIDADE3 FOREIGN KEY (HABILIDADE3) REFERENCES HABILIDADE(NOME_HABILIDADE),
    CONSTRAINT FK_HABILIDADE4 FOREIGN KEY (HABILIDADE4) REFERENCES HABILIDADE(NOME_HABILIDADE)
);

CREATE TABLE EQUIPE(
    TREINADOR_ID int,
    POKEMON int,
    CONSTRAINT PK_EQUIPE PRIMARY KEY(TREINADOR_ID, POKEMON),
    CONSTRAINT FK_TREINADOR_ID FOREIGN KEY(TREINADOR_ID) REFERENCES TREINADOR(TREINADOR_ID),
    CONSTRAINT FK_POKEMON FOREIGN KEY(POKEMON) REFERENCES POKEMON(POKEMON_ID)
);

CREATE TABLE BATALHA(
    BATALHA_ID serial,
    POKEMON1 int,
    POKEMON2 int,
    CONSTRAINT PK_BATALHA PRIMARY KEY(BATALHA_ID),
    CONSTRAINT FK_POKEMON1 FOREIGN KEY(POKEMON1) REFERENCES POKEMON(POKEMON_ID),
    CONSTRAINT FK_POKEMON2 FOREIGN KEY(POKEMON2) REFERENCES POKEMON(POKEMON_ID)
);

CREATE TABLE NPC(
    NPC_ID serial PRIMARY KEY NOT NULL,
    TREINADOR int,
    LOCALIDADE int NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    GINASIO VARCHAR(50),
    INFO VARCHAR(150) NOT NULL,
    CONSTRAINT FK_TREINADOR FOREIGN KEY(TREINADOR) REFERENCES TREINADOR(TREINADOR_ID),
    CONSTRAINT FK_LOCALIDADE FOREIGN KEY(LOCALIDADE) REFERENCES LUGAR(LOCALIZACAO)
);

CREATE TABLE LOOT(
    LOOT_ID serial PRIMARY KEY,
    NOME_ITEM VARCHAR(60) NOT NULL,
    QUANTIDADE int NOT NULL,
    LOCALIDADE int NOT NULL,
    CONSTRAINT FK_LOCALIDADE FOREIGN KEY(LOCALIDADE) REFERENCES LUGAR(LOCALIZACAO)
);

CREATE TABLE GINASIO(
    NOME_GINASIO VARCHAR(50) PRIMARY KEY,
    LIDER_ID int NOT NULL,
    TIPO1 int NOT NULL,
    TIPO2 int,
    CIDADE int NOT NULL,
    LOOT int NOT NULL,
    CONSTRAINT FK_LIDER_ID FOREIGN KEY(LIDER_ID) REFERENCES NPC(NPC_ID),
    CONSTRAINT FK_TIPO1_GIN FOREIGN KEY(TIPO1) REFERENCES TIPO(TIPO_ID),
    CONSTRAINT FK_TIPO2_GIN FOREIGN KEY(TIPO2) REFERENCES TIPO(TIPO_ID),
    CONSTRAINT FK_CIDADE FOREIGN KEY(CIDADE) REFERENCES LUGAR(LOCALIZACAO),
    CONSTRAINT FK_LOOT FOREIGN KEY(LOOT) REFERENCES LOOT(LOOT_ID)
);


CREATE TABLE BATALHADOR(
	NPC_TREINADOR_ID int PRIMARY KEY,
	TIPO1 int NOT NULL,
	TIPO2 int,
	LOCALIDADE int NOT NULL,
	LOOT int,


	CONSTRAINT FK_NPC_BATALHADOR FOREIGN KEY(NPC_TREINADOR_ID) REFERENCES NPC(NPC_ID),
	CONSTRAINT FK_LOCALIDADE FOREIGN KEY(LOCALIDADE) REFERENCES LUGAR(LOCALIZACAO),
	CONSTRAINT FK_TIPO1_BATALHADOR FOREIGN KEY(TIPO1) REFERENCES TIPO(TIPO_ID),
	CONSTRAINT FK_TIPO2_BATALHADOR FOREIGN KEY(TIPO2) REFERENCES TIPO(TIPO_ID),
	CONSTRAINT FK_LOOT FOREIGN KEY(LOOT) REFERENCES LOOT(LOOT_ID)
);


CREATE TABLE POKECENTER(
	POKECENTER_ID serial PRIMARY KEY,
	CURA_DISPONIVEL int,
	LOCALIDADE int NOT NULL,
	INFO VARCHAR(50),

	CONSTRAINT FK_LOCALIDADE FOREIGN KEY(LOCALIDADE) REFERENCES LUGAR(LOCALIZACAO)
);



CREATE TABLE ENFERMEIRAJOY(
	POKECENTER_ID int,
	NPC_ID int,

	CONSTRAINT PK_ENFERMEIRAJOY PRIMARY KEY(POKECENTER_ID, NPC_ID),
	CONSTRAINT FK_POKECENTER_ID FOREIGN KEY(POKECENTER_ID) REFERENCES POKECENTER(POKECENTER_ID),
	CONSTRAINT FK_NPC_ID FOREIGN KEY(NPC_ID) REFERENCES NPC(NPC_ID)
);



CREATE TABLE POKEMART(
	POKEMART_ID int PRIMARY KEY,
	ITENS_DISPONIVEIS int,
	LOCALIDADE int NOT NULL,
	INFO VARCHAR(50),

	CONSTRAINT FK_LOCALIDADE FOREIGN KEY(LOCALIDADE) REFERENCES LUGAR(LOCALIZACAO)
);


CREATE TABLE LOJISTA(
	POKEMART_ID int ,
	NPC_ID int,

	CONSTRAINT PK_LOJISTA PRIMARY KEY(POKEMART_ID, NPC_ID),
	CONSTRAINT FK_POKEMART_ID FOREIGN KEY(POKEMART_ID) REFERENCES POKEMART(POKEMART_ID),
	CONSTRAINT FK_NPC_ID FOREIGN KEY(NPC_ID) REFERENCES NPC(NPC_ID)
);


CREATE TABLE ITENS_VENDIDOS(
	POKEMART_ID int ,
	ITEM_ID VARCHAR(60),
	QUANTIDADE int,
	PRECO int,

	CONSTRAINT PK_ITENS_VENDIDOS PRIMARY KEY(POKEMART_ID, ITEM_ID),
	CONSTRAINT FK_POKEMART_ID FOREIGN KEY(POKEMART_ID) REFERENCES POKEMART(POKEMART_ID),
	CONSTRAINT FK_ITEM_ID FOREIGN KEY(ITEM_ID) REFERENCES ITENS_COMUNS(NOME_ITEM)
);

COMMIT;
